version: '3.8'

services:
  postgres-addressautocomplete:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    networks:
      - network-addressautocomplete
  
  redis-addressautocomplete:
    image: redis:latest
    ports:
      - "6380:6379"
    networks:
      - network-addressautocomplete

  api-addressautocomplete:
    build:
      context: ./AddressAutoComplete
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - postgres-addressautocomplete
      - redis-addressautocomplete
    environment:
      POSTGRES_CONNECTION_STRING: Host=postgres;Port=5432;Database=mydatabase;User Id=myuser;Password=mypassword
      REDIS_CONNECTION_STRING: redis:6380
    networks:
      - network-addressautocomplete

networks:
  network-addressautocomplete:
    driver: bridge
